server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm_main_db
    username: ewm_user
    password: ewm_password

stats-server:
  url: http://stats-server:9090

logging:
  level:
    root: INFO
    ru.practicum.explorewithme.main: DEBUG