version: '3.8'
services:
  stat-server:
    build: stat/stat-server
    container_name: ewm-stats-server-compose
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JAVA_OPTS=-Duser.timezone=UTC

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db-compose
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: stat_user
      POSTGRES_PASSWORD: stat_password
      POSTGRES_DB: ewm_stats_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
